[part1-example1]
interpreter = "cpython-314"
code = "aoc202504.py"
input_path = "example1.txt"
value = 13
solved = true
duration = 6.84609985910356e-05
parse_duration = 9.57300653681159e-06

[part2-example1]
interpreter = "cpython-314"
code = "aoc202504.py"
input_path = "example1.txt"
value = 43
solved = true
duration = 0.0005260979814920574
parse_duration = 9.57300653681159e-06
