[part1-example1_part1]
interpreter = "cpython-314"
code = "aoc202511.py"
input_path = "example1_part1.txt"
value = 5
solved = true
duration = 1.6048026736825705e-05
parse_duration = 5.285954102873802e-06

[part2-example2_part2]
interpreter = "cpython-314"
code = "aoc202511.py"
input_path = "example2_part2.txt"
value = 2
solved = true
duration = 5.655601853504777e-05
parse_duration = 8.200004231184721e-06
