[part1-example1]
input_path = "example1.txt"
value = 11
duration = 0.00024518500140402466
parse_duration = 2.5244997232221067e-05

[part2-example1]
input_path = "example1.txt"
value = ""
duration = 0.004128612010390498
parse_duration = 2.5244997232221067e-05
