[part1-example1]
input_path = "example1.txt"
value = 6
duration = 9.791998309083283e-06
parse_duration = 2.0024002878926694e-05

[part2-example1]
input_path = "example1.txt"
value = 2
duration = 1.787200744729489e-05
parse_duration = 2.0024002878926694e-05
