[part1-example1]
input_path = "example1.txt"
value = 58
duration = 0.0013131119922036305
parse_duration = 3.475099219940603e-05

[part2-example1]
input_path = "example1.txt"
value = ""
duration = 2.3809989215806127e-06
parse_duration = 3.475099219940603e-05
