[part1-example1]
input_path = "example1.txt"
value = 15
duration = 7.830200775060803e-05
parse_duration = 3.083799674641341e-05

[part2-example1]
input_path = "example1.txt"
value = 1_134
duration = 0.00035891799780074507
parse_duration = 3.083799674641341e-05
