[part1-example1]
interpreter = "cpython-314"
code = "aoc202502.py"
input_path = "example1.txt"
value = 1_227_775_554
solved = true
duration = 1.902101212181151e-05
parse_duration = 2.328399568796158e-05

[part2-example1]
interpreter = "cpython-314"
code = "aoc202502.py"
input_path = "example1.txt"
value = 4_174_379_265
solved = true
duration = 0.00013459398178383708
parse_duration = 2.328399568796158e-05
