[part1-example1]
input_path = "example1.txt"
value = 605
duration = 1.5594996511936188e-05
parse_duration = 0.00026418999186716974

[part2-example1]
input_path = "example1.txt"
value = 982
duration = 1.359300222247839e-05
parse_duration = 0.00026418999186716974
