[challenge]
name = "Advent of Code"
url = "https://adventofcode.com/"
icon = "‚≠ê"

[patterns]
solve = "aoc20[1-9][0-9][0-2][0-9]{suffix}.py"
input = "input.txt"
example = "example*.txt"

[code]
parse_function = "parse_data"
solve_functions = ["part1", "part2"]

[template]
file_name = "aoc{event:04d}{puzzle:02d}.py"
docstring = "AoC {puzzle}, {event}: {name}."

[template.readme]
challenge = "{root_dir}/README.template"
language = "{root_dir}/README.language.template"
event = "{root_dir}/README.event.template"

[languages.python]
language_dir = "{root_dir}/python/src"
icon = "üêç"

[languages.elixir]
language_dir = "{root_dir}/elixir/lib"
icon = "üíß"
