[part1-example1]
input_path = "example1.txt"
value = 820
duration = 1.5419936971738935e-06
parse_duration = 8.136004908010364e-06

[part2-example1]
input_path = "example1.txt"
value = 120
duration = 4.53690008725971e-05
parse_duration = 8.136004908010364e-06
