[part1-example1]
input_path = "example1.txt"
value = 64
duration = 6.704199768137187e-05
parse_duration = 2.3663000320084393e-05

[part2-example1]
input_path = "example1.txt"
value = 58
duration = 0.012335210994933732
parse_duration = 2.3663000320084393e-05
