[part1-example1]
input_path = "example1.txt"
value = 2
duration = 5.889000021852553e-06
parse_duration = 2.238100569229573e-05

[part2-example1]
input_path = "example1.txt"
value = 5
duration = 1.3874989235773683e-05
parse_duration = 2.238100569229573e-05
