[part1-example1]
input_path = "example1.txt"
value = 99
duration = 0.00010256899986416101
parse_duration = 6.577000021934509e-06

[part2-example1]
input_path = "example1.txt"
value = 44
duration = 6.386601307895035e-05
parse_duration = 6.577000021934509e-06
