[part1-example1]
input_path = "example1.txt"
value = 41
duration = 3.8893005694262683e-05
parse_duration = 2.7411006158217788e-05

[part2-example1]
input_path = "example1.txt"
value = 6
duration = 0.00029717799043282866
parse_duration = 2.7411006158217788e-05
