[part1-example1]
input_path = "example1.txt"
value = 2_660
duration = 7.62200215831399e-06
parse_duration = 0.0005322530050761998

[part2-example1]
input_path = "example1.txt"
value = 1_564
duration = 0.0007331009983317927
parse_duration = 0.0005322530050761998
