[part1-example1]
interpreter = "cpython-314"
code = "aoc202503.py"
input_path = "example1.txt"
value = 357
solved = true
duration = 1.1752999853342772e-05
parse_duration = 1.9579892978072166e-06

[part2-example1]
interpreter = "cpython-314"
code = "aoc202503.py"
input_path = "example1.txt"
value = 3_121_910_778_619
solved = true
duration = 2.619597944431007e-05
parse_duration = 1.9579892978072166e-06
