[part1-example1]
input_path = "example1.txt"
value = 4
duration = 7.538998033851385e-06
parse_duration = 1.8393999198451638e-05

[part1-example2]
input_path = "example2.txt"
value = 8
duration = 1.4024990377947688e-05
parse_duration = 3.270499291829765e-05

[part1-example3]
input_path = "example3.txt"
value = 70
duration = 6.300499080680311e-05
parse_duration = 8.632699609734118e-05

[part1-example4]
input_path = "example4.txt"
value = 80
duration = 8.529699698556215e-05
parse_duration = 0.00031944800866767764

[part2-example1]
input_path = "example1.txt"
value = 1
duration = 3.485400520730764e-05
parse_duration = 1.8393999198451638e-05

[part2-example2]
input_path = "example2.txt"
value = 1
duration = 3.630100400187075e-05
parse_duration = 3.270499291829765e-05

[part2-example3]
input_path = "example3.txt"
value = 8
duration = 0.0001854089932749048
parse_duration = 8.632699609734118e-05

[part2-example4]
input_path = "example4.txt"
value = 10
duration = 0.00012448699271772057
parse_duration = 0.00031944800866767764
