[part1-example1]
interpreter = "cpython-314"
code = "aoc202505.py"
input_path = "example1.txt"
value = 3
solved = true
duration = 7.294001989066601e-06
parse_duration = 8.095987141132355e-06

[part2-example1]
interpreter = "cpython-314"
code = "aoc202505.py"
input_path = "example1.txt"
value = 14
solved = true
duration = 1.5236000763252378e-05
parse_duration = 8.095987141132355e-06
