[part1-example1]
interpreter = "cpython-314"
code = "aoc202510.py"
input_path = "example1.txt"
value = 7
solved = true
duration = 2.754997694864869e-05
parse_duration = 2.1761981770396233e-05

[part2-example1]
interpreter = "cpython-314"
code = "aoc202510.py"
input_path = "example1.txt"
value = 33
solved = true
duration = 0.00391784799285233
parse_duration = 2.1761981770396233e-05
