[part1-example1]
input_path = "example1.txt"
value = 31
duration = 0.00020813499577343464
parse_duration = 6.287300493568182e-05

[part2-example1]
input_path = "example1.txt"
value = 29
duration = 0.00020357999892439693
parse_duration = 6.287300493568182e-05
