[part1-example1]
input_path = "example1.txt"
value = 43_210
duration = 0.006746059007127769
parse_duration = 6.259011570364237e-06

[part1-example2]
input_path = "example2.txt"
value = 54_321
duration = 0.009851399008766748
parse_duration = 7.68899917602539e-06

[part1-example3]
input_path = "example3.txt"
value = 65_210
duration = 0.011941243006731384
parse_duration = 1.2481003068387508e-05

[part1-example4]
input_path = "example4.txt"
value = -28_142_426
duration = 0.03482635300315451
parse_duration = 1.2019008863717318e-05

[part1-example5]
input_path = "example5.txt"
value = 18_036
duration = 0.13901594499475323
parse_duration = 2.043499262072146e-05

[part2-example1]
input_path = "example1.txt"
value = 98_765
duration = 0.007171694989665411
parse_duration = 6.259011570364237e-06

[part2-example2]
input_path = "example2.txt"
value = -1_234
duration = 0.009954444001778029
parse_duration = 7.68899917602539e-06

[part2-example3]
input_path = "example3.txt"
value = 76_543
duration = 0.012814380999770947
parse_duration = 1.2481003068387508e-05

[part2-example4]
input_path = "example4.txt"
value = 139_629_729
duration = 0.034210135010653175
parse_duration = 1.2019008863717318e-05

[part2-example5]
input_path = "example5.txt"
value = 18_216
duration = 0.1646550369914621
parse_duration = 2.043499262072146e-05
