[part1-example1]
interpreter = "cpython-314"
code = "aoc202501.py"
input_path = "example1.txt"
value = 3
solved = true
duration = 2.5769986677914858e-06
parse_duration = 4.330009687691927e-06

[part1-example2]
interpreter = "cpython-314"
code = "aoc202501.py"
input_path = "example2.txt"
value = 2
solved = true
duration = 2.134009264409542e-06
parse_duration = 4.083005478605628e-06

[part2-example1]
interpreter = "cpython-314"
code = "aoc202501.py"
input_path = "example1.txt"
value = 6
solved = true
duration = 8.154980605468154e-06
parse_duration = 4.330009687691927e-06

[part2-example2]
interpreter = "cpython-314"
code = "aoc202501.py"
input_path = "example2.txt"
value = 11
solved = true
duration = 4.444009391590953e-06
parse_duration = 4.083005478605628e-06
