[part1-example1]
input_path = "example1.txt"
value = 34_241
duration = 3.130990080535412e-06
parse_duration = 4.842993803322315e-06

[part2-example1]
input_path = "example1.txt"
value = 51_316
duration = 1.1255004210397601e-05
parse_duration = 4.842993803322315e-06
