[part1-example1]
input_path = "example1.txt"
value = 8
duration = 0.00011725399235729128
parse_duration = 1.0050993296317756e-05

[part2-example1]
input_path = "example1.txt"
value = ""
duration = 0.0006256180058699101
parse_duration = 1.0050993296317756e-05
