[part1-example1]
input_path = "example1.txt"
value = 588
duration = 1.5744455370004289
parse_duration = 7.485999958589673e-06

[part2-example1]
input_path = "example1.txt"
value = 309
duration = 0.6836938789929263
parse_duration = 7.485999958589673e-06
