[part1-example1]
input_path = "example1.txt"
value = 12
duration = 4.295399412512779e-05
parse_duration = 2.162996679544449e-06

[part2-example1]
input_path = "example1.txt"
value = 12
duration = 1.669299672357738e-05
parse_duration = 2.162996679544449e-06
