[part1-example1]
input_path = "example1.txt"
value = 2
duration = 4.738991265185177e-06
parse_duration = 9.010997018776834e-06

[part2-example1]
input_path = "example1.txt"
value = 1
duration = 7.881011697463691e-06
parse_duration = 9.010997018776834e-06
