[part1-example1]
input_path = "example1.txt"
value = 26
duration = 1.7950995243154466e-05
parse_duration = 0.00013526099792215973

[part2-example1]
input_path = "example1.txt"
value = 61_229
duration = 0.00042591500096023083
parse_duration = 0.00013526099792215973
